services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  web:
    build:
      context: ./admin_panel
      dockerfile: Dockerfile
    volumes:
      - ./admin_panel:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - .env  

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot:/app
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
